server:
  netty:
    port: 6666
    connection-timeout: 10000
  port: 8081



netty:
  boss:
    thread:
      count: 2
  worker:
    thread:
      count: 256
  tcp:
    port: 6667
    bufferSize: 1048576
  so:
    backlog: 1024