@startuml
start
:RTG上报异常(R508/提箱前发生故障);
:IECS收到异常上报,保存异常信息;
:IECS根据远控台分配算法找到具体远控设备;
if (存在空闲的远控设备?) is (是) then
  :IECS响应单机RTG成功,将远控设备信息给单机RTG;
  :IECS发送单机RTG信息和异常信息给具体远控;
else (否)
  :IECS响应单机RTG等待,单机RTG固定时间轮询访问IECS申请远控;
  :继续走寻找远控算法逻辑，直到找到具体远控设备;
endif
:远控台收到单机RTG信息,则根据自己业务逻辑处理!;
if (可以修复故障?) is (是) then
  :修复故障后继续正常作业任务流程;
else (否)
  :不可修复故障,则走取消任务流程;
  :任务执行结果反馈-已取消,并上报已取消原因,请求IECS;
  :IECS收到已取消后,将取消原因发送给TOS,请求TOS的RJMC, moveStatus=3中止任务;
  :修改IECSRTG设备状态为暂停作业;
endif
stop
@enduml
