@startuml
start
:RTG上报异常(R504-提箱后设备故障);
:IECS收到异常上报,保存异常信息;
:IECS根据远控台分配算法找到具体远控设备;
if (存在空闲的远控设备?) is (是) then
  :IECS响应单机RTG成功,将远控设备信息给单机RTG;
  :IECS发送单机RTG信息和异常信息给具体远控;
else (否)
  :IECS响应单机RTG等待,单机RTG固定时间轮询访问IECS申请远控;
  :继续走寻找远控算法逻辑，直到找到具体远控设备;
endif
:远控台收到单机RTG信息和异常信息,则根据自己业务逻辑处理!;
:远控人员手动操作放箱;
:完成作业通知IECS，走任务执行结果反馈已完成流程;
:IECS收到已完成，调用TOS的RJML接口完成任务,moveStatus=2或4;
:修改IECSRTG设备状态为暂停作业;
stop
@enduml
