@startuml
start
:RTG上报异常(R507-起始位置或目标位置不可用);
:IECS收到异常上报,保存异常信息;
:IECS根据远控台分配算法找到具体远控设备;
if (存在空闲的远控设备?) is (是) then
  :IECS响应单机RTG成功,将远控设备信息给单机RTG;
  :IECS发送单机RTG信息和异常信息给具体远控;
else (否)
  :IECS响应单机RTG等待,单机RTG固定时间轮询访问IECS申请远控;
  :继续走寻找远控算法逻辑，直到找到具体远控设备;
endif
:远控台收到单机RTG信息和异常信息,则根据自己业务逻辑处理!;
:RTG通知IECS走取消的任务执行结果反馈,上报取消原因;
:IECS任务执行结果反馈已取消流程，继续后续任务;
stop
@enduml
