spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
    dynamic:
      lazy: true
      primary: master
      # 配置全局druid参数，请按需配置
      druid:
        initial-size: 5
        max-active: 8
        min-idle: 3
        max-wait: 1000
        validation-query: 'select 1'
      datasource:
        master:
          username: root
          password: liqi347158
          url: jdbc:mysql://localhost:3306/ry-cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useAffectedRows=true&allowPublicKeyRetrieval=true
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          username: root
          password: liqi347158
          url: jdbc:mysql://localhost:3306/ry-config?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useAffectedRows=true&allowPublicKeyRetrieval=true
          driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.jz.test.redistest
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/**/*.xml


logging:
  level:
    com.jz.test.redistest: debug