server:
  port: 8099
spring:
  application:
    name: redis-test
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  cache:
    type: redis
#  redis:
#    cluster:
#      nodes:
#        - 10.140.20.151:6379
#        - 10.140.20.152:6379
#        - 10.140.20.153:6379
#        - 10.140.20.154:6379
#        - 10.140.20.155:6379
#        - 10.140.20.156:6379
#      max-redirects: 3
#    timeout: 5000
#    password: admin
#    lettuce:
#      pool:
#        max-active: -1
#        max-wait: -1
#        max-idle: 1000
#        min-idle: 100
  redis:
    host: 122.112.220.88
    port: 31079
    timeout: 5000
    password: admin
    lettuce:
      pool:
        max-active: -1
        max-wait: -1
        max-idle: 1000
        min-idle: 100

  redis2:
    host: 10.140.20.151
    port: 6379
    timeout: 5000
    password: admin
    lettuce:
      pool:
        max-active: -1
        max-wait: -1
        max-idle: 1000
        min-idle: 100

  profiles:
    include: dynamicMysql

rediscount: 200

RealDataReport-spout:
  redisNodes: 10.140.20.151:6379,10.140.20.152:6379,10.140.20.153:6379,10.140.20.154:6379,10.140.20.155:6379,10.140.20.156:6379

