@startuml
'https://plantuml.com/sequence-diagram

autonumber

西虹桥 -> IOT: 通过PID:PID=911上报车辆信息
IOT -> 边缘端设备: 发送车辆信息
alt 设备 == "RTG"
边缘端设备 -> IECS: 发送车辆信息到IECS处理RTG指令业务
group IECS处理RTG指令业务
IECS -> IECS: 西虹桥感知到的车辆的RTG任务,下发任务到边缘端
IECS -> RTG: RTG任务下发流程
IECS -> IECS: 触发RTG调度进箱区事件
IECS -> UWB: RTG调度流程
IECS -> IECS: 记录RTG任务下发异常事件(西虹桥触发)

end
else 设备 == "QC"
边缘端设备 -> IECS: 记录桥吊发现外集卡异常
end

边缘端设备 --> IOT: PID=919收到车辆信息回执
IOT --> 西虹桥: PID=919收到车辆信息回执
@enduml